[package]
name = "archivefs"
version = "0.1.3"
authors = ["André Ligné <hi@andreligne.se>"]
build = "build.rs"

[dependencies]
libc = "0.2"
walkdir = "2"
tempdir = "0.3"
regex = "1"

[build-dependencies]
bindgen = "0.53.1"

[lib]
name = "archivefs"
crate-type = ["dylib", "rlib"]
