[package]
name = "archivefs"
version = "0.0.1"
authors = ["André Ligné <hi@andreligne.se>"]
build = "build.rs"

[dependencies]
libc = "0.2"
walkdir = "2"

[lib]
name = "archivefs"
crate-type = ["dylib"]
