name: Rust
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install system deps
      run: sudo apt-get update && sudo apt-get install -y libarchive-dev libfuse-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
